# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='maplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapName', models.CharField(max_length=255)),
                ('mapDesc', models.TextField()),
                ('mapLat', models.CharField(max_length=255)),
                ('mapLng', models.CharField(max_length=255)),
                ('mapTel', models.CharField(max_length=255)),
                ('mapAddr', models.CharField(max_length=255)),
            ],
        ),
    ]
