# Generated by Django 3.0.6 on 2020-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puliapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maplist1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapName', models.CharField(max_length=60)),
                ('mapDesc', models.TextField()),
                ('mapLat', models.CharField(max_length=20)),
                ('mapLng', models.CharField(max_length=20)),
                ('mapTel', models.CharField(max_length=20)),
                ('mapAddr', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('schoolClassChinese', models.CharField(max_length=20)),
                ('seatNumber', models.CharField(max_length=20)),
                ('studentID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('identityCard', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=2)),
                ('birth_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='mapadmin',
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapAddr',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapLat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapLng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapTel',
            field=models.CharField(max_length=20),
        ),
    ]
